<?php
$smpl_xml=simplexml_load_file('test.xml');
echo ($smpl_xml);
sdgjksj
sahdsh
drhdrhggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
